#! /usr/bin/env node

require("coffee-script");
var program = require("commander");

var build_action = require("./actions/build");

program
   .option("-o, --output <path>", "change the output directory, defaults to '/bin'")
   .option("-c, --chdir <path>", "change the working directory")
   .option("-e, --empty", "empties output directory (excluding .git and .gitignore)")
   .option("-r, --run <command>", "runs command after successful build")
   .option("-d, --debug", "does not minify JS and CSS")
   .option("-s, --silent", "suppresses console.logs");

program
   .command("build")
   .description("compile to PhoneGap compliant app")
   .action(function (cmd) {
      build_action(program);
   });

program.parse(process.argv);