#! /usr/bin/env node

require("coffee-script");
var program = require("commander");

var load = require("./utils/loader");

var build_action = require("./actions/build");
var watch_action = require("./actions/watch");

program
   .option("-o, --output <path>", "change the output directory, defaults to '/bin'")
   .option("-c, --chdir <path>", "change the working directory")
   .option("-e, --empty", "empties output directory (excluding .git and .gitignore)", false)
   .option("-r, --run <command>", "runs command after successful run")
   .option("-d, --debug", "does not minify JS and CSS", false)
   .option("-s, --silent", "suppresses console.logs", false);

program
   .command("build")
   .description("compile files into output directory")
   .action(function (cmd) {
      config = load(program);
      build_action(config);
   });

program
   .command("watch")
   .description("watch for file changes and compile files that change")
   .action(function (cmd) {
      config = load(program);
      watch_action(config);
   });


program.parse(process.argv);